/// Flutter icons MyFlutterApp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/github.ttf
///
/// 
/// * Octicons, Copyright (C) 2020 by GitHub Inc.
///         Author:    GitHub
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  https://primer.style/octicons/
///
import 'package:flutter/widgets.dart';

class GitHubIcons {
  GitHubIcons._();

  static const _kFontFam = 'GitHubIcons';
  static const _kFontPkg = null;
  static const IconData github = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github_action = IconData(0xf373, fontFamily: _kFontFam, fontPackage: _kFontPkg);

}
